%YAML 1.1
---
gfVersion: v3.0
class: workflow

# Workflow Metadata
name: Minimap2 Short Read Workflow
description: Minimap2 short read sequence alignment workflow
git: https://github.com/geneflow-workflows/minimap2-gf3
version: '2.22-02'

publish:
- align

# Workflow Inputs (i.e., files/folders)
inputs:
  reads:
    description: Input directory containing FASTQ files
    default: ./data/reads
  reference:
    description: Reference sequence FASTA file
    default: ./data/reference.fa

# Workflow Parameters
parameters: 
  threads:
    description: Number of CPU threads for alignment
    default: 2

# Workflow Apps Defined Inline
apps:
  minimap2_align:
    inputs:
      input:
      pair:
      reference:
    parameters:
      threads:
      output:
    images:
      minimap2_docker: quay.io/biocontainers/minimap2:2.22--h5bf99c6_0
      minimap2_singularity: docker://quay.io/biocontainers/minimap2:2.22--h5bf99c6_0
    execution:
      pre:
      - run: mkdir -p ${LOG_FULL}
      methods:
      - name: docker
        if: 
        - in_path: docker
        commands:
        - type: docker
          image: minimap2_docker
          run: >-
            minimap2 -ax sr -t ${THREADS} ^${REFERENCE} ^${INPUT} ^${PAIR} 
            > ${OUTPUT_FULL}
            2> ${LOG_FULL}/${OUTPUT_BASE}-minimap2-align.stderr

      - name: singularity
        if: 
        - in_path: singularity
        commands:
        - type: singularity
          image: minimap2_singularity
          run: >-
            minimap2 -ax sr -t ${THREADS} ^${REFERENCE} ^${INPUT} ^${PAIR} 
            > ${OUTPUT_FULL}
            2> ${LOG_FULL}/${OUTPUT_BASE}-minimap2-align.stderr

## Workflow Steps
steps:
  align:
    app: minimap2_align
    depend: []
    map:
      uri: ${workflow->reads}
      regex: (.*)_(R|)1(.*)\.((fastq|fq)(|\.gz))$
    template:
      input: ${workflow->reads}/${1}_${2}1${3}.${4}
      pair: ${workflow->reads}/${1}_${2}2${3}.${4}
      reference: ${workflow->reference}
      threads: ${workflow->threads}
      output: ${1}.sam
...
